### ISSUE TITLE
Block 5 missing in first message of every file

### ISSUE THREAD

**Issue by nickidk4** [a-fas/mt940js#14]
Block 5 is missing in the first swift message of every input file.

I can see block 5 is in the input file, but it is not returned in the parser.

**Comment by a-fas** [comment]
mmmm, example ?
cli shows fine in this test - https://github.com/a-fas/mt940js/blob/master/test/testX.mt940

**Comment by nickidk4** [comment]
I grab each swift message from my input file with regex, because I get extra lines of information before each swift message from sending bank.
And I did not concatenate each swift message with a "/n" and this caused it somehow to not catch the first block 5.
After adding "/n" it works perfectly!
I currently don't have any other errors :D
