### ISSUE TITLE
Supplementary details are not parsed in :61

### ISSUE THREAD

**Issue by vasyas** [a-fas/mt940js#15]
Fragment is
:61:170406D000000001001,69N541NONREF
NL72RABO0104510633

A possible fix in fork https://github.com/vasyas/mt940js

**Comment by sbcgua** [comment]
Yeap, a bug.
I pushed a test for your case (fails now). Welcome to PR your fix :)

**Comment by a-fas** [comment]
Yeap, a bug.
I pushed a test for your case (fails now). Welcome to PR your fix :)

**Comment by vasyas** [comment]
Thanks, created.

**Comment by vasyas** [comment]
Fixed, closing
