### ISSUE TITLE
Non-swift data, indicated by :NS:

### ISSUE THREAD

**Issue by dommmel** [a-fas/mt940js#18]
Hi there,

thanks for making and supporting this! 

I have a mt940 file with (what apparently is) non-swift, indicated by `:NS:`, data. In my case it holds all the transaction details. I have no clue if my bank handles this correctly. But here I am having to deal with it.

```
:61:1908090809D000000000825,00FMSCNONREF
:NS:01My Street 17
02City and Region
03Invoice Nr. # 20190808/1 for Rent August 2019
04
05
06
07
08
09
10
11
12
13
14
15
16
17E-Banking Order for Foo Corp
```
My javascript is a bit rusty but could you maybe point me into a direction were I would start If I wanted to parse this with your lib? 

Cheers!

**Comment by a-fas** [comment]
Hi @dommmel , sorry for late response, quite busy these days.
Have a look at the pull request above. If OK, I'll merge.
In particular there is an example (can be called by `./cli test/test-with-NS.mt940x`) and the unit test with the expected results

Briefly - if NS happens inside the transaction context it is added to nonSwift attribute. From there you can parse it further

![image](https://user-images.githubusercontent.com/11891106/67590292-5a47f900-f763-11e9-8a93-d319ed79c65a.png)

**Comment by a-fas** [comment]
should be solved, closing
