### ISSUE TITLE
Add UMD build for use with unpkg.com

### ISSUE THREAD

**Issue by culmat** [a-fas/mt940js#24]
see https://unpkg.com/#workflow

**Comment by a-fas** [comment]
try https://unpkg.com/mt940js@1.4.0-beta.0/dist/index.min.js

**Comment by a-fas** [comment]
see also https://github.com/a-fas/mt940js/blob/v1.4/index.sample.html

**Comment by culmat** [comment]
Hello Alexander,
works like a charm. 
Thx a lot.
Matthias
