### ISSUE TITLE
Suport for /xxx/ tags in field 86

### ISSUE THREAD

**Issue by a-fas** [a-fas/mt940js#4]

**Comment by reckertz** [comment]
For the first time I got a cancellation of a cash payment - the module does not like that.
:61:1812171217DR800,00N003NONREF
:86:083?00BARGELDAUSZAHLUNG KASSE?102149?3037050299
:61:1812171217RDR800,00N068NONREF
:86:899?00STORNO BAR KASSE?102149?3037050299
BARGELDAUSZAHLUNG meant cash payment, this booking was false, so STORNO BAR KASSE is the cancellation of this payment.
The following error is thrown:
    static parse(dcmark, amountStr) {
        if ('DC'.indexOf(dcmark) < 0) {
            **throw Error('Wrong debit/credit mark: ${dcmark}');**
Is it possible to fix that?

**Comment by a-fas** [comment]
implemented
