### ISSUE TITLE
Tag 64 and 65 missing

### ISSUE THREAD

**Issue by nickidk4** [a-fas/mt940js#6]
If swift message contains tag 64 or 65, it fails and can,t create tag.

![image](https://user-images.githubusercontent.com/15192005/51375053-1570a100-1b05-11e9-83ba-02681355cb2d.png)

![image](https://user-images.githubusercontent.com/15192005/51383735-8c646480-1b1a-11e9-9681-839f5413ab24.png)

Error happens here in tags.js
![image](https://user-images.githubusercontent.com/15192005/51375135-58327900-1b05-11e9-8be5-d198e6f09aa7.png)

Would be great if support for tag 64 and 65 could be implemented.

**Comment by a-fas** [comment]
Yes, will have a look :) Could you attach an example ? This would be helpful

**Comment by a-fas** [comment]
Can I say that Forward Available = Closing Available by default and Closing Available = Closing by default. I mean when the explicit tag are missing in the statement ?

**Comment by a-fas** [comment]
Have a look at the latest code (not released as npm package yet)

**Comment by a-fas** [comment]
published, see also new postParseMiddleware feature :)
