### ISSUE TITLE
Support for block 1, 2, 3 and 5

### ISSUE THREAD

**Issue by nickidk4** [a-fas/mt940js#7]
Is it possible to implement support for block 1, 2, 3 and 5?

**Comment by a-fas** [comment]
potentially yes, but not that trivial.

1. do you have a good reference to standard about blocks ?
2. not that clear where should block data be in returned results
3. not clear what to do in case of multiple messages (multiple set of blocks) in the input

any ideas ?

**Comment by nickidk4** [comment]
I think the best returned result would be something like this:
 _- It would not break the current returned block 4 results._

```
var statements = {
    block1: {   // BASIC HEADER BLOCK
        blockIdentifier: "",
        applicationIdentifier: "",
        serviceIdentifier: "",
        ltIdentifier: "",   // logical terminal address of the message source
        sessionNumber: "",
        sequenceNumber: "",
    },

    block2: {   // APPLICATION HEADER BLOCK
        blockIdentifier: "",
        ioIdentifier: "",   // I = input, O = output
        messageType: "",
        inputTime: "",
        mir: "",
        outputDate: "",
        outputTime: "",
        messagePriority: "",
    },

    block3: {   // USER HEADER BLOCK
        blockIdentifier: "",
        bankingPriority: "",
        messageUserReference: "",
    },

    block5: {   // TRAILER BLOCK
       checkSum: "", 
    },

    transactionReference: "",
    relatedReference: "",
    accountIdentification: "",
    number: "",
    number: "",
    number: "",
    openingBalanceDate: "",
    closingBalanceDate: "",
    closingAvailableBalanceDate: "",
    forwardAvailableBalanceDate: "",
    statementDate: "",
    currency: "",
    openingBalance: "",
    closingBalance: "",
    closingAvailableBalance: "",
    forwardAvailableBalance: "",
    informationToAccountOwner: "",

    transactions: [{
        date: "",
        amount: "",
        isReversal: "",
        currency: "",
        details: "",
        transactionType: "",
        reference: "",
        entryDate: "",
        fundsCode: "",
        bankReference: "",
        extraDetails: "",
        structuredDetails: "",
    }]
}
```

**Comment by a-fas** [comment]
this approach won't do. First of all it changes the interface heavily and the library is used in some places. Secondly there might be no blocks, thirdly as I mentioned the blocks may interrupt statement at the middle - this would mean collecting the data over several blocks. The library will loose simplicity and focus. 

The blocks is certainly a kind of auxiliary data for the time being. I think maybe it will be an additional attribute in the statement, maybe with raw block tags ... as there can be multiple sets of them. I'll think when I have some more time.

Anyway thank for the links, but could you check the second link please - it didn't work.

**Comment by nickidk4** [comment]
I don't have any swifts without block 1, 2, 3 and 5.
Block 3 is optional though.
But the same block can't appear multiple times in same swift/statement.

I fixed link.

If this can't be implemented, I will have to implement it in my own project.

**Comment by nickidk4** [comment]
Nice!
I see your block 5 looks a little different in your test than mine does. I will give you some examples I come across.
`-}{5:{CHK:761XXXX7A283}{DLM:}{CAC:VALIDATION SUCCESS}}`
`-}{5:{CHK:2B0F3613F273}{PDE:}{CAC:VALIDATION SUCCESS}}`
`-}{5:{CHK:E7C9E7309377}{CAC:VALIDATION SUCCESS}}`

I dont have MAC in any of my examples :)

**Comment by a-fas** [comment]
Have a look (same branch - msg-blocks).

- So now, if the statement has message blocks, then the resulting object will have `messageBlocks` attribute in form of `{ '1': { value: 'message...' } }` (see the last test in parser.test.js)
- Messages themselves are not parsed. Currently don't have time for this. Feel free to implement on-site or PR ;) I left a placeholder - `_parseMessageBlockFields` method, but it's empty now and needs thinking in terms of output structure and internal logic. I think block messages logic should go to a separate file
- Message blocks in the middle of statement (between tags 20 and 65) are not supported at the moment (I've seen this, but hopefully it is rare)

If code looks OK, I'll merge and release at npm

**Comment by nickidk4** [comment]
This is great!
I have my own functions to split the message block values into separate values.
This should be pushed to npm :)

**Comment by a-fas** [comment]
ok, published as 1.3.0 :tada:

**Comment by nickidk4** [comment]
Do you plan on splitting the message blocks up more, or do you leave that to the user?
Just want to know if I should close issue or if it is still under development? :)

**Comment by a-fas** [comment]
well, maybe in future, not now for sure, don't have time. But PRs are welcomed ;)
I think please close this one, this was about support for blocks in general. But if you open a separate one for *parsing* of message structure - that would be better. Just not to forget

**Comment by nickidk4** [comment]
I have 1 issue though..
I can't grab value of messageBlocks['5'].value..
Block 1,2 and 3 works fine though.
```
console.log(s.messageBlocks['1'].value);   // WORKS
console.log(s.messageBlocks['5'].value);   // DOES NOT WORK - Returns Error: null
```

I tried encapsulating it in a try-catch and then it worked without throwing error?
