### ISSUE TITLE
Problem with cancellation of cash payment in 61

### ISSUE THREAD

**Issue by reckertz** [a-fas/mt940js#8]
For the first time I got a cancellation of a cash payment - the module does not like that.
:61:1812171217DR800,00N003NONREF
:86:083?00BARGELDAUSZAHLUNG KASSE?102149?3037050299
:61:1812171217RDR800,00N068NONREF
:86:899?00STORNO BAR KASSE?102149?3037050299
BARGELDAUSZAHLUNG meant cash payment, this booking was false, so STORNO BAR KASSE is the cancellation of this payment.
The following error is thrown:
static parse(dcmark, amountStr) {
if ('DC'.indexOf(dcmark) < 0) {
throw Error('Wrong debit/credit mark: ${dcmark}');
Is it possible to fix that?

**Comment by a-fas** [comment]
yes, will have a look. Seems like there is `R` mark for reversals. It is even in [official spec](https://www2.swift.com/knowledgecentre/publications/us9m_20180720/2.0?topic=ajf006.htm%23mt940-6-field-61) :)

**Comment by reckertz** [comment]
hi Alexander, Thanksgiving you that you Take Care, Rolf



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Alexander Tsybulsky
Betreff: Re: [a-fas/mt940js] Problem with cancellation of cash payment in 
61 (#8)
Datum: 18.01.2019, 19:50 Uhr
An: a-fas/mt940js
Cc: reckertz, Author



yes, will have a look. Seems like there is R mark for reversals. It is even 
in official spec
<https://www2.swift.com/knowledgecentre/publications/us9m_20180720/2.0?topic=ajf006.htm%23mt940-6-field-61> 
:)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/a-fas/mt940js/issues/8#issuecomment-455649068> , or 
mute the thread

**Comment by a-fas** [comment]
try the latest code (not released via npm yet, will do later)

**Comment by a-fas** [comment]
published, see also new postParseMiddleware feature :)

**Comment by nickidk4** [comment]
This works and should be closed :)

**Comment by a-fas** [comment]
great :)
